### ISSUE TITLE
Issue when converting Excelfile with missing data to DataFrame

### ISSUE THREAD

**Issue by cosimoizzo** [JuliaData/DataFrames.jl#1878] opened 2019-07-08 12:32 UTC
Hi, 

Julia crashes when I try to convert an Excel file with missing to DataFrame.

I am using Julia 1.0.4 on Windows, DataFrame package is v0.18.2, FileIO is v1.0.6.

I create a simple excel file: cell A1 = a, cell A2 = 1, cell A3 = "", cell A4 = 2.

Then run the following command in Julia:

`using FileIO, DataFrames`
`a = load("Example.xlsx", "Sheet1") `
`a |> DataFrame`

a returns an Excel File 3 x 1 with header a, and entries [1; #NA; 2]. 
But the second line to turn it into a DataFrame returns the following error and closes Julia.

Please, see below the report:

`Unreachable reached at 000000002CF1CD80
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x2cf1cd80 -- macro expansion at C:\Users\user\.julia\packages\Tables\NEFJq\src\utils.jl:51 [inlined]
eachcolumn at C:\Users\user\.julia\packages\Tables\NEFJq\src\utils.jl:46 [inlined]
buildcolumns at C:\Users\user\.julia\packages\Tables\NEFJq\src\fallbacks.jl:93
in expression starting at no file:0
macro expansion at C:\Users\user\.julia\packages\Tables\NEFJq\src\utils.jl:51 [inlined]
eachcolumn at C:\Users\user\.julia\packages\Tables\NEFJq\src\utils.jl:46 [inlined]
buildcolumns at C:\Users\user\.julia\packages\Tables\NEFJq\src\fallbacks.jl:93
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
columns at C:\Users\user\.julia\packages\Tables\NEFJq\src\fallbacks.jl:174 [inlined]
#DataFrame#366 at C:\Users\user\.julia\packages\DataFrames\m9gd9\src\other\tables.jl:33
unknown function (ip: 000000002CF1B266)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2312
Type at C:\Users\user\.julia\packages\DataFrames\m9gd9\src\other\tables.jl:20
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
|> at .\operators.jl:813
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
do_call at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:430
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:697
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:806
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000003FA913BF)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:805
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:622
eval at .\boot.jl:319
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
#28 at .\task.jl:259
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 117141848 (Pool: 117110046; Big: 31802); GC: 253`

**Comment by fipelle** [comment] 2019-07-08 12:35
+1 

Same issue on Mojave (10.4.4) with Julia 1.0.3.

I think it might be correlated with what @simonbyrne mentioned in https://github.com/JuliaLang/julia/issues/29639.

**Comment by bkamins** [comment] 2019-07-08 12:42
@davidanthoff - do you have an experience with this? (it seems to be related to Queryverse-DataFrames.jl interface)

**Comment by quinnj** [comment] 2019-07-08 13:55
I'll take a look

**Comment by davidanthoff** [comment] 2019-07-09 09:50
I can't replicate the crash, but it seems that `DataValue` is not being converted to `Union{T,Missing}` correctly:
```

julia> using ExcelFiles, DataFrames

julia> a = load("Book1.xlsx", "Sheet1")
3x1 Excel file
a
───
1.0
#NA
2.0

julia> DataFrame(a)
3×1 DataFrame
│ Row │ a   │
│     │ Any │
├─────┼─────┤
│ 1   │ 1.0 │
│ 2   │ #NA │
│ 3   │ 2.0 │
```
Maybe Tables.jl is not handling the `DataValue{Any}` case properly here?

Another question is why ExcelFiles.jl isn't properly typing the column as a number, I'll look into that.

**Comment by quinnj** [comment] 2019-07-09 12:41
It might be worth trying the examples again, since a new Tables.jl release was just tagged within the last 4 hours or so. I also couldn't reproduce the crash, but didn't notice the `DataValue{Any}` case, so I'll keep looking as well.

**Comment by davidanthoff** [comment] 2019-07-09 14:09
I just checked with the latest version of Tables.jl, and I think there is just a bug in Tables.jl there (and I have the same bug in TableTraitsUtils.jl as well!): https://github.com/JuliaData/Tables.jl/issues/109.

**Comment by quinnj** [comment] 2019-07-15 14:32
I just merged a fix for this in Tables.jl and tagged a new release; if someone wants to try the latest Tables.jl, you can do `] add Tables#master` which will pull down the fix. To go back to the current release of Tables.jl, you just do `] free Tables`.

**Comment by bkamins** [comment] 2019-07-15 14:45
Great. Thank you!

**Closed** 2019-07-17 12:45 UTC
