### ISSUE TITLE
ENH: Allow use of colon operator to slice ranges by column names

### ISSUE THREAD

**Issue by sglyon** [JuliaData/DataFrames.jl#393] opened 2013-11-06 04:30 UTC
This seems like reasonable functionality that is currently not implemented:

```
julia> df = DataFrame(quote
       A = [1:10]
       B = [1:10] .* 2
       C = [1:10] .* 3
       end
       )
10x3 DataFrame:
          A  B  C
[1,]      1  2  3
[2,]      2  4  6
[3,]      3  6  9
[4,]      4  8 12
[5,]      5 10 15
[6,]      6 12 18
[7,]      7 14 21
[8,]      8 16 24
[9,]      9 18 27
[10,]    10 20 30


julia> df["A":"B"]
ERROR: no method colon(ASCIIString,ASCIIString)
```

I would expect the return value to be something like:

```
10x2 DataFrame:
          A  B
[1,]      1  2
[2,]      2  4
[3,]      3  6
[4,]      4  8
[5,]      5 10
[6,]      6 12
[7,]      7 14
[8,]      8 16
[9,]      9 18
[10,]    10 20
```

**Comment by quinnj** [comment] 2017-09-07 04:18
Yeah, supporting `(:col1):(:col3)` is clearly not going to happen these days, but if someone wants to take a stab at a string macro or use of the `..` operator, I think it could be entertained. Part of the issue is that DataFrames has moved to symbol indexing, and `:col1..:col3` won't work because it tries to parse the `..:` operator, which isn't valid.

**Comment by bkamins** [comment] 2019-07-25 01:07
I would close it. We have fixed standard indexing API. If someone needs to do it `Tables.columnindex` can be used to get what is needed (it is not the shortest syntax imaginable but it is good enough IMO):
```
start, stop = Tables.columnindex(Ref(df), (:col1, :col2))
select(df, start:stop)
```

Feel free to reopen this if you disagree.

**Comment by nalimilan** [comment] 2019-07-25 13:27
I think we should support something like [JuliaDB's `select(t, Between(start, stop))`](https://juliacomputing.github.io/JuliaDB.jl/latest/basics/#Selectors-1). That's something that also exists in dplyr.

**Comment by bkamins** [comment] 2019-07-25 13:46
OK. Then `Between` should be moved to DataAPI.jl first. I am OK to add this.

**Comment by bkamins** [comment] 2019-07-25 13:57
@quinnj + @piever: do you think it should go to DataAPI.jl or Tables.jl?

**Comment by piever** [comment] 2019-07-26 19:58
I don't have a strong preference either way, maybe DataAPI makes the most sense as it really is just an API. Slgihtly off-topic, I would suggest to also add the `All` selector, which takes the union of all selectors: https://juliacomputing.github.io/JuliaDB.jl/latest/api/#IndexedTables.All (if one wants to select two intervals for example).

**Comment by bkamins** [comment] 2019-07-26 20:06
Sure - adding `All` has been a pending request. So let us move both `Between` and `All` to DataAPI.jl.

@quinnj - are you OK with this?

**Comment by quinnj** [comment] 2019-07-26 20:13
Sure

**Comment by bkamins** [comment] 2019-08-11 08:50
Added in https://github.com/JuliaData/DataFrames.jl/pull/1914

**Closed by bkamins** 2019-08-11 08:50 UTC
