### ISSUE TITLE
repeated "signal (11): Segmentation fault", but randomly happens

### ISSUE THREAD

**Issue by zhongyunde** [JuliaData/DataFrames.jl#2289] opened 2020-06-15 04:45 UTC
A simplified task is described like this: 
```
using DataStructures 
using DataFrames
vt = Union{Int64, Float64, Bool}
d = OrderedDict{Symbol, vt}(:a=>0.0, :b=>0.0, :c=>0.0)
df = DataFrame([vt, vt, vt], [:a, :b, :c], 0)
for i = 1:500
    d[:a] = rand()
    d[:b] = rand() 
    d[:c] = rand()
    push!(df, d) 
end 
```
There is no issues when run this task individually. But when it runs to process 2000 independent tasks on 12 threads for 4 hours (note: each task runs on its own thread), problem happens. It throws repeated "signal (11): Segmentation fault", but randomly. The exception message is below: 

```
signal (11): Segmentation fault
...
jl_unwrap_unionall at /buildworker/worker/package_linux64/build/src/jltypes.c:955
jl_typemap_assoc_exact at /buildworker/worker/package_linux64/build/src/julia_internal.h:1025 [inlined]
jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:2270 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2319
iterate at /home/london/.julia/packages/OrderedCollections/P6ntV/src/ordered_dict.jl:417
iterate at ./abstractdict.jl:60 [inlined]
_all at ./reduce.jl:819 [inlined]
all at ./reduce.jl:815 [inlined]
#push!#186 at /home/london/.julia/packages/DataFrames/kwVTY/src/dataframe/dataframe.jl:1337
push! at /home/london/.julia/packages/DataFrames/kwVTY/src/dataframe/dataframe.jl:1315
```
I suspected the problem came from the code (dataframe.jl, Line 1337) 
```
all(x -> x isa AbstractString, keys(row))
```
So I made some changes to it today, and after that it worked very well. No more Segmentation fault for today. I do no know whether the problem is permanently fixed or not, but I can tell the changes helped.  
```
#dataframe.jl, Line 1337
- if row isa AbstractDict && all(x -> x isa AbstractString, keys(row))
+ if row isa AbstractDict && (eltype(row).types[1] <: AbstractString)
     row = (;(Symbol.(keys(row)) .=> values(row))...) 
  end 
...
#dataframe.jl, Line 1345 
- if row isa AbstractDict && !all(x -> x isa Symbol, keys(row))
+ if row isa AbstractDict && !(eltype(row).types[1] <: Symbol)
       throw(ArgumentError("when `cols == :union` all keys of row must be Symbol"))
  end
```

I have been running this program for months without a problem until I upgraded Julia to 1.4.2 recently together with the DataFrames package. Here is my current package list: 
```
Status `~/.julia/environments/v1.4/Project.toml`
  [dce04be8] ArgCheck v2.0.0
  [336ed68f] CSV v0.6.2
  [a93c6f00] DataFrames v0.21.2
  [864edb3b] DataStructures v0.17.17
  [31a5f54b] Debugger v0.6.4
  [31c24e10] Distributions v0.23.4
  [587475ba] Flux v0.10.4
  [59287772] Formatting v0.4.1
  [38e38edf] GLM v1.3.9
  [cd3eb016] HTTP v0.8.15
  [77172c1b] HttpCommon v0.5.0
  [7073ff75] IJulia v1.21.2
  [033835bb] JLD2 v0.1.13
  [682c06a0] JSON v0.21.0
  [aa1ae85d] JuliaInterpreter v0.7.21
  [b27032c2] LibCURL v0.6.0
  [e6f89c97] LoggingExtras v0.4.1
  [ee78f7c6] Makie v0.11.0
  [6f286f6a] MultivariateStats v0.7.0
  [08abe8d2] PrettyTables v0.9.0
  [1a8c2f83] Query v0.12.2
  [c35d69d1] SMTPClient v0.6.0
  [65254759] StatsMakie v0.2.2
  [f269a46b] TimeZones v1.2.0
  [29a6e085] Wavelets v0.9.0
  [6462fe0b] Sockets 
  [10745b16] Statistics 
```
Additional information: 
1. "export JULIA_NUM_THREADS=12" is setup in ".bashrc" to enable 12 threads
2. Fedora Linux box with 64G
3. Before the code change, I already tried to "instantiate" packages from scratch after the Julia 1.4.2 upgrade

**Comment by bkamins** [comment] 2020-06-15 08:57
Your code is not thread safe and you most likely hit race condition problem. But I assume that your original code looks differently. Can you please pass your original code please?

In particular both:
```
    d[:a] = rand()
    d[:b] = rand() 
    d[:c] = rand()
```
nor
```
    push!(df, d) 
```

are not thread safe. So unless you allocate both `d` and `df` individually per thread you are likely to have problems (and the fact that Segmentation Fault shows up is just a random thing and it could equally well show up in your changed code in different circumstances).

Note in particular that the second line you change is not even executed in your code (it is in the branch that is not invoked at all).

**Comment by zhongyunde** [comment] 2020-06-15 20:35
Thank you for your quick response, Bogumił. Sorry about the distraction brought by the mutli-threading information in my last post. I should have posted more detailed codes: 

```
using DataStructures
using DataFrames

struct Feed
    id::Int64
    src::DataFrame;
    srcdict::OrderedDict{Symbol, Float64};
    function Feed(id::Int64)
        srcdict=OrderedDict{Symbol, Float64}(); 
        for i in [:a, :b, :c]
            srcdict[i] = 0.0;
        end
        src = DataFrame([Float64, Float64, Float64], [:a, :b, :c], 0);
        return new(id, src, srcdict);
    end
end

function update!(x::Feed)
    # heavy calculation irrelevant to this problem
    x.srcdict[:a] = 0.0  # live feed and the calculation results in production 
    x.srcdict[:b] = 0.0  # live feed and the calculation results in production 
    x.srcdict[:c] = 0.0  # live feed and the calculation results in production 
    push!(x.src, x.srcdict)
end

function run!(x::Feed)
    for i = 1:1000
        update!(x)
    end
end

function run!(x::Vector{Feed})
    id = Threads.Atomic{Int}(0)
    Threads.@threads for i in 1:length(x)
        Threads.atomic_add!(id, 1)
        @info "thread $(Threads.threadid()) ==> processing feed $(feeds[i].id)"
        run!(feeds[i]);
    end
end

tot = 100
feeds = Vector{Feed}(undef, tot)
for i = 1:tot
    feeds[i] = Feed(i)
end
run!(feeds)
```
So each individual dataframe is only accessed by an independent thread
```
push!(x.src, x.srcdict)
```

Also, I knew that there is a second approach to avoid the "Segmentation fault": 
``` 
-push!(x.src, x.srcdict) 
+push!(x.src, (; x.srcdict...))
```
that is, to convert Dictionary to NamedTuple before calling "push!" so that it will by pass the 
```
all(x -> x isa AbstractString, keys(row)) # dataframe.jl Line 1337
```

You are correct about the second line change, which is irrelevant and unnecessary. Thanks. 

Overall, I can confirm that: 
1. There is no issues for months until my recent upgrade of Julia 1.4.2 with upgrade of dataframe and other packages
2. Everything works as good as before if I avoid the code
```
all(x -> x isa AbstractString, keys(row)) # dataframe.jl Line 1337
```
3. The problem happens on both of my computers, Fedora Linux, and iMac 

but the problem might come from my computers, or from other packages (for example, ordered_dict.jl) . I will post back if eventually I figure out the underlying problem. Thanks.

**Comment by bkamins** [comment] 2020-06-15 21:32
This is strange. In general this line (as I am sure you know) should be not related to DataFrames.jl, but is a code from Base.

I would try running this code e.g on Julia 1.3 or Julia nightly to chceck if it is reproduced.

On my side I will update DataFrames.jl not to run this check if it is not necessary.

**Comment by bkamins** [comment] 2020-06-15 21:56
Can you try checking out #2290 and verifying if it resolves the issue? (it is a workaround only, but maybe it will help)

PS. also note that there is a `keytype` function that you can use.

**Comment by zhongyunde** [comment] 2020-06-16 17:39
I checked out #2290 (3dae640ef8b42931d1bfdd1b73cd1615a2e7b688) and ran it twice for the whole night. Both worked very well without any "segmentation fault". Thanks. 
```
(workaround) pkg> st DataFrames
Status `~/github/workaround/Project.toml`
  [a93c6f00] DataFrames v0.21.2 [`~/.julia/dev/DataFrames`]
```
I debugged into the base's "all" function before and did not see issues. I though the "all" function might multi-threading itself when it is possible. That was why I put my multi-threading information in my original post, but I did not look into deeper. 

I had many "segmentation fault" issues when developing my project months ago from many other packages, most of which caused by Julia upgrading. It should not happen, right?, but it did from time to time on my computer. The easiest way for me to fix it is to delete the "./julia/packages" and "./julia/complied" folders, then bring them back by "pkg> instantiate". But unfortunately this approach did not work for this issue, otherwise I will not post it here. 

So the workaround #2290 worked very well for my case. Since it was not a bug of DataFrames package, I think #2289 can be closed for now. Thanks for your help. 

I did not realize that there is a ```keytype``` function, but I know now. Thanks.

**Comment by bkamins** [comment] 2020-06-16 17:43
Thank you for a detailed report.

Maybe you have also checked if the performance of the code improved (it should).

I will automatically close it when #2290 is merged (so that at least we are sure we have not forgotten to implement a workaround - as sometimes we have to; e.g. see https://github.com/JuliaData/DataFrames.jl/pull/2072 which is caused by a long standing bug in Julia Base we were not able to track down, but we also implemented a workaround there).

**Comment by zhongyunde** [comment] 2020-06-16 17:58
Confirmed. The run time was reduced from 252 minutes to 220 minutes, that is about 13% off for my case. Great work!. Thanks.

**Comment by bkamins** [comment] 2020-06-23 20:48
Closing as #2290 is merged

**Closed** 2020-06-23 20:48 UTC
Labels: question
