### ISSUE TITLE
Type piracy for Base.reduce with empty Union{}[]

### ISSUE THREAD

**Issue by filchristou** [JuliaData/DataFrames.jl#3294] opened 2023-02-28 13:27 UTC
Using `Vector{Union{}}` for the `Base.reduce` function calls the `DataFrames` `Base.reduce` version and fails.

MWE:
start a fresh julia kernel:
```julia
(@v1.8) pkg> activate --temp
  Activating new project at `/tmp/jl_YKSpeo`

julia> Base.reduce(vcat, Union{}[]; init=Vector{Int}()) # works fine
Int64[]

julia> using DataFrames
 │ Package DataFrames not found, but a package named DataFrames is available from a registry. 
 │ Install package?
 │   (jl_YKSpeo) pkg> add DataFrames 
 └ (y/n/o) [y]: y
    ...bla bla bla...

julia> Base.reduce(vcat, Union{}[]; init=Vector{Int}()) # errors
ERROR: MethodError: no method matching reduce(::typeof(vcat), ::Vector{Union{}}; init=Int64[])
Closest candidates are:
  reduce(::typeof(vcat), ::AbstractVector{<:AbstractVecOrMat}) at abstractarray.jl:1650 got unsupported keyword argument "init"
  reduce(::typeof(vcat), ::Union{Tuple{AbstractDataFrame, Vararg{AbstractDataFrame}}, AbstractVector{<:AbstractDataFrame}}; cols, source) at ~/.julia/packages/DataFrames/LteEl/src/abstractdataframe/abstractdataframe.jl:1847 got unsupported keyword argument "init"
  reduce(::Any, ::AbstractArray; kw...) at reducedim.jl:406
  ...
Stacktrace:
 [1] kwerr(::NamedTuple{(:init,), Tuple{Vector{Int64}}}, ::Function, ::Function, ::Vector{Union{}})
   @ Base ./error.jl:165
 [2] top-level scope
   @ REPL[3]:1
```

My system:
```julia
(jl_YKSpeo) pkg> st
Status `/tmp/jl_YKSpeo/Project.toml`
  [a93c6f00] DataFrames v1.5.0

julia> versioninfo()
Julia Version 1.8.4
Commit 00177ebc4fc (2022-12-23 21:32 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i5-1235U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 12 virtual cores
```

There is already some talk in the julia repo for this general problem https://github.com/JuliaLang/julia/issues/10326
Essentially Union{} can subtype anything so it's quite easy to discover type piracy all over..
However, I didn't use to have this error until some time ago. Did something change ?

**Comment by filchristou** [comment] 2023-02-28 13:42
For some reason https://github.com/JuliaLang/julia/issues/10326 is already closed. I don't understand why. But there is also this related issue that is still open https://github.com/JuliaLang/julia/issues/22850

**Comment by bkamins** [comment] 2023-02-28 14:38
This is in general a known issue with `Union{}` (not in this specific case, but in general). The question is if you report it, because you identified it "theoretically", but this is indeed a problem in some real code.

The question is because:
* if it is just a theoretical question then we will leave it as is;
* if it breaks some code in practice then we need to think how to resolve it.

See `Base.isambiguous` - the case you mention is explicitly handled via kwarg there for the exact reason that `Union{}` is known to be problematic.

**Comment by bkamins** [comment] 2023-02-28 15:36
So I will close it for now, as, as you say - the `Union{}` is an issue on the language level.

Now, regarding your problem. The issue is most likely that:
```
[el for el in generate(...)]
```
is problematic in your case. What you describe can happen only if:
* `generate(...)` does not generate anything;
* the compiler cannot infer type of values returned by `generate(...)` (i.e. it is type unstable)

However, from your code it seems that `MyType[el for el in generate(...)]` should fix this.

**Closed by bkamins** 2023-02-28 15:36 UTC
Labels: question

**Comment by filchristou** [comment] 2023-02-28 15:50
many thanks you for the tips and the fast response !
