### ISSUE TITLE
DataFrames breaks jupyter pdf export

### ISSUE THREAD

**Issue by tbenst** [JuliaData/DataFrames.jl#1581] opened 2018-10-31 08:52 UTC
I've found that while dataframes displays beautifully in Jupyter HTML, that if one tries to export a pdf then all cells following and including the dataframe are truncated. Is there a way to avoid this behavior? Or perhaps this is a fixable bug? Let me know if I can help troubleshoot. Thanks for the great package!

**Comment by pdeffebach** [comment] 2018-10-31 16:35
Thanks for the bug report. Does the pdf exporting work in python with pandas?

**Comment by pdeffebach** [comment] 2018-11-01 00:16
I can reproduce, in the sense that I also get an error. However for me it just breaks, without even giving ugly output. Here is the error from the log file:

```
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/t1cmtt.fd)
! Text line contains an invalid character.
l.296         │     │ ^^[
                             [90mInt64^^[[39m │ ^^[[90mInt64^^[[39m │
? 
! Emergency stop.
l.296         │     │ ^^[
                             [90mInt64^^[[39m │ ^^[[90mInt64^^[[39m │
No pages of output.
Transcript written on notebook.log.
```

Looking at the .tex file produced directly is this: (screenshot because of the invisible character `<0x1b>`

<img width="786" alt="screen shot 2018-10-31 at 7 15 37 pm" src="https://user-images.githubusercontent.com/23196228/47825707-4bda2380-dd41-11e8-991f-f279dea539eb.png">


@bkamins It looks like the text coloring on the new type annotations in the output is messing with Latex's `verbatim` environment?

**Comment by bkamins** [comment] 2018-11-01 07:39
This is not a problem with the new header (the error would be present also before if you had `missing` in the output) but the issues that IPython stores output only in two formats: `text/html` for displaying and `text/plain` and the latter is used when attempting PDF export. `text/latex` is not written (although we provide it). I will open an issue with IJulia for this.

**Comment by bkamins** [comment] 2018-11-08 13:53
The problem is fixed on IJulia master (I have just checked it works correctly).

Thanks to @stevengj for fixing this.

The only question is that currently in LaTeX output we do not ship out column type information in tables (we decided to leave it out as we thought that in LaTeX documents it would not look nice - as typically you want to embed such table in some report where type information is not relevant, and only print the types in `text/plain` and `text/html`).

If you have a preference to print column type information in `text/latex` please open a separate issue or make a PR for a review.

**Closed by bkamins** 2018-11-08 13:53 UTC
