### ISSUE TITLE
Extremely slow show in the REPL

### ISSUE THREAD

**Issue by fredrikekre** [JuliaData/DataFrames.jl#2605] opened 2021-01-21 14:01 UTC
I made a silly mistake and obtained a `DataFrame` that takes forever to show in the REPL.
```julia
julia> using DataFrames, Dates

julia> function make_df()
           d0 = now()
           df = DataFrame(name=String[], time=DateTime[], status=Bool[])
           for i in 0:30*24*30*3
               d = d0 + Minute(i)
               for s in ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l")
                   #for chk in 1:3
                       push!(df, (name=s, time=d, status=rand(Bool)))
                   #end
               end
           end
           return df
       end;

julia> df = make_df();

julia> @time display(df)
[...]
  2.648168 seconds (7.65 M allocations: 463.344 MiB, 8.59% gc time, 99.82% compilation time)

julia> @time display(df)
[...]
  0.008935 seconds (7.24 k allocations: 7.006 MiB)

julia> df2 = transform(df, :time => x -> Date.(x) => :date);

julia> @time display(df2)
[...]
  67.131361 seconds (519.57 M allocations: 19.960 GiB, 4.10% gc time, 0.42% compilation time)

julia> @time display(df2)
[...]
  68.410671 seconds (518.96 M allocations: 19.924 GiB, 3.85% gc time)
```
Note the compile time percentage. I first thought it might be mostly compile time, but it takes as long in the second run (0% compile time).

**Comment by bkamins** [comment] 2021-01-21 14:07
Unfortunately I can reproduce it :(. It is most likely a problem with PrettyTables.jl. If I have some more conclusions I will report.

**Comment by bkamins** [comment] 2021-01-21 14:18
@ronisbr it seems that cropping takes a lot of time - probably you should avoid cropping for rows that you know you are not going to display anyway (as this is the reason of the slowdown most likely). The core of the problem is that:
```
pretty_table(df2.time_function)
```
is prohibitively slow (which is unrelated with DataFrames.jl)

**Comment by ronisbr** [comment] 2021-01-21 15:56
> @ronisbr it seems that cropping takes a lot of time - probably you should avoid cropping for rows that you know you are not going to display anyway (as this is the reason of the slowdown most likely).

It is not related to cropping, because it only crop rows and columns that I know they will be printed. However, the conversion to text seems extremely slow. Take a look of what you get with:

```
print(df2.time_function[1])
```

It takes forever and I am not sure why.

**Comment by ronisbr** [comment] 2021-01-21 15:58
Note the time it took to convert those cells to text:

```
julia> @time string(df2[1,4]);
  1.152588 seconds (10.38 M allocations: 393.023 MiB, 8.65% gc time)
```

**Comment by ronisbr** [comment] 2021-01-21 16:23
Well, I will do this: if the column size has a maximum width, then I can call `sprint` with `:limit` set to true. This will improve things.

**Comment by ronisbr** [comment] 2021-01-21 16:50
Well, unfortunately `print` does not take into account `displaysize` when IO has `:limit => true`:

```julia
julia> print(IOContext(stdout, :compact => true, :displaysize => (200,200), :limit => true), a)
[0.514337 0.176874 … 0.954236 0.123093; 0.0287126 0.468991 … 0.506993 0.795948; … ; 0.232503 0.636545 … 0.607239 0.311314; 0.807105 0.561979 … 0.322937 0.0579306]
julia> print(IOContext(stdout, :compact => true, :displaysize => (1,1), :limit => true), a)
[0.514337 0.176874 … 0.954236 0.123093; 0.0287126 0.468991 … 0.506993 0.795948; … ; 0.232503 0.636545 … 0.607239 0.311314; 0.807105 0.561979 … 0.322937 0.0579306]
```

Hence I have a proposal. Create a keyword in PrettyTables like `limit_cells_with_big_arrays` that will convert cells that are arrays to string using the property `:limit => true` if the length of that array is larger than a number (let's say 30, which can be another option). This will be by default `true`, so that no modification in DataFrames is needed. The only problem is that it will break DataFrames with arrays larger than 30.

If everyone is OK with this approach, then I will implement it. If not, any suggestion?

**Comment by bkamins** [comment] 2021-01-21 16:51
OK - I am transferring the issue to PrettyTables.jl then. Display changes are considered non-breaking in DataFrames.jl :smile:.

**Comment by bkamins** [comment] 2021-01-21 16:52
For some reason I cannot do the transfer. @ronisbr - could you please do it?

**Comment by ronisbr** [comment] 2021-01-21 16:54
> For some reason I cannot do the transfer. @ronisbr - could you please do it?

It seems it can only be transferred to repositories in JuliaData. I have not transferred PrettyTables to that organization yet, sorry :D Can we let this open here until I fix it?

**Comment by bkamins** [comment] 2021-01-21 17:05
Sure - we can keep it here :smile:.

**Comment by quinnj** [comment] 2021-01-21 17:41
Happy to facilitate transferring the repo if everyone agrees. I can add @ronisbr as a JuliaData member

**Comment by ronisbr** [comment] 2021-01-21 18:14
> Happy to facilitate transferring the repo if everyone agrees. I can add @ronisbr as a JuliaData member

I think I am already a member o JuliaData. However, I can't still transfer it to ronisbr/PrettyTables.jl. Maybe I am missing something?

**Comment by fredrikekre** [comment] 2021-01-21 18:29
See https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#about-repository-transfers
To create new repos in an org I believe you have to be an owner (unless there is now some permission step inbetween member and owner). It is of course possible to demote to member after the transfer.

**Comment by ronisbr** [comment] 2021-01-21 18:30
Oh, I was talking about transferring the issue, not the repo :D Sorry... I think I have the permissions needed to transfer PrettyTables.jl to JuliaData.

**Comment by fredrikekre** [comment] 2021-01-21 19:29
Ah ok, perhaps I misunderstood https://github.com/JuliaData/DataFrames.jl/issues/2605#issuecomment-764820175 then. Yea, you can only transfer issues between repos in the same organization. Just close this and reopen over there if you want.

**Comment by ronisbr** [comment] 2021-01-23 12:28
This should be fixed in PrettyTable.jl. I will submit a PR to update the compat bounds to 0.11 and also to remove that floating point alignment that is not required anymore.

**Closed** 2021-01-24 12:48 UTC
Labels: display, performance, priority

**Comment by ronisbr** [comment] 2021-01-24 12:52
@fredrikekre `master` should take care of this problem now. Can you please test?

I got this results:

```julia
julia> using DataFrames, Dates

julia> function make_df()
                  d0 = now()
                  df = DataFrame(name=String[], time=DateTime[], status=Bool[])
                  for i in 0:30*24*30*3
                      d = d0 + Minute(i)
                      for s in ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l")
                          #for chk in 1:3
                              push!(df, (name=s, time=d, status=rand(Bool)))
                          #end
                      end
                  end
                  return df
              end;^C

julia> using DataFrames, Dates

julia> function make_df()
           d0 = now()
           df = DataFrame(name=String[], time=DateTime[], status=Bool[])
           for i in 0:30*24*30*3
               d = d0 + Minute(i)
               for s in ("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l")
                   #for chk in 1:3
                       push!(df, (name=s, time=d, status=rand(Bool)))
                   #end
               end
           end
           return df
       end;

julia> df = make_df();

julia> @time display(df)
[...]
  2.745614 seconds (8.03 M allocations: 481.562 MiB, 7.38% gc time, 99.40% compilation time)

julia> @time display(df)
[...]
  0.004966 seconds (8.74 k allocations: 7.072 MiB)

julia> df2 = transform(df, :time => x -> Date.(x) => :date);

julia> @time display(df2)
[...]
  0.257198 seconds (612.78 k allocations: 43.181 MiB, 96.40% compilation time)

julia> @time display(df2)
[...]
  0.008882 seconds (32.65 k allocations: 8.082 MiB)
```
