### ISSUE TITLE
Performance Issues in 0.7.0

### ISSUE THREAD

**Issue by RobertRosca** [JuliaData/DataFrames.jl#1353] opened 2018-02-14 18:04 UTC
Hi,

I'm having some performance issues on 0.7.0, and I think they're related to my use of DataFrames.

A loop in one of my functions uses to take around 3 seconds to complete, but on 0.7.0 it takes around five minutes. Here's a [Gist with two notebooks, the first on 0.6.2 and second on 0.7.0, showing the issue](https://gist.github.com/RobertRosca/945a7ae8c55fe4672f2ee338827070a9).

Running `@time` on both shows:

```
304.391396 seconds (58.30 M allocations: 9.124 GiB, 0.60% gc time) - 0.7.0
  3.272925 seconds (4.96 M allocations: 2.385 GiB, 17.22% gc time) - 0.6.2
```

Here's [another Gist using BenchmarkTools.jl](https://gist.github.com/RobertRosca/425d87112b942599995106fbb38d8e3d) looking at just one value from the for loop, it showed that areas of the loop using DataFrames are an order of magnitude slower, and use about an order of magnitude more allocations.

Is this an issue with DataFrames in 0.7.0, or is this some known result of a change in 0.7.0 that means I should be doing that loop differently? Thanks for any help.

**Comment by nalimilan** [comment] 2018-02-14 19:17
Thanks for the detailed report. I can reproduce using e.g. `DataFrame([], DataFrames.Index(Symbol[]))`. I think it's just due to the many deprecation warnings, which are very costly. For example, using `Vector{Any}(uninitialized, 0)` instead of `Vector{Any}(0)` reduces allocations a lot.

Help to fix deprecations would be welcome (https://github.com/JuliaData/DataFrames.jl/pull/1233 was a first step).

**Comment by RobertRosca** [comment] 2018-02-15 01:04
Sure, I'd love to help, but I'm still a bit new to GitHub.

Is there some way to fork a pull request, or include it in my fork, so I could easily build on the changes #1233 would implement?

**Comment by nalimilan** [comment] 2018-02-15 21:04
Don't worry about #1233, it's outdated anyway. I've just prepared https://github.com/JuliaData/DataFrames.jl/pull/1354 using Femtocleaner so that you don't waste your time doing this manually, but once it's merged you'll just have to pull master to make a new PR.

**Comment by RobertRosca** [comment] 2018-02-16 13:23
Awesome, I'll start working on it now, thanks

**Comment by nalimilan** [comment] 2018-09-20 17:15
I think this is fixed now, but please reopen if not.

**Closed by nalimilan** 2018-09-20 17:15 UTC
