### ISSUE TITLE
Cannot export dataframe after replace!

### ISSUE THREAD

**Issue by yoh-meyers** [JuliaData/DataFrames.jl#3097] opened 2022-07-07 12:34 UTC
Hello,

After researching the docs, I believe that best method to replace all values in a given column, is to use `replace!`.

My issue is that I have a module, where I would like to generalise this behaviour for many different dataframes.
Hence a summary of my code is as below. Please note that I have 2 different functions for calling `replace!` and saving to Feather.

```julia
df::DataFrames.DataFrame = _table  #temporary copy
replace!(df.a, old => new)

# Replace global _table in order to save to Feather in different function
global _table = df
Feather.write(joinpath(Main.Settings[:FEATHER_DIR], _table_name * ".feather"), _table)
```

However upon re-loading the Feather file, dataframe is corrupted, as length of column a, matches number of unique entries of column. I tried printing dataframe before saving and get same error.

Am I using method wrongly?

Thank you

**Comment by bkamins** [comment] 2022-07-07 14:53
Can you please provide a minimal complete working example (i.e. something that I can copy-paste and see the error) reproducing the error? What you have passed should not error, however I have two comments:
1. the code you have shared will not work. It would only work as a part of a local scope (like a `function` or `let`)
2. the operation `df::DataFrames.DataFrame = _table` is very tricky, and such code is not advised. If `_table` is a `DataFrame` this operation is no-op (no copy is made), but if `_table` is `SubDataFrame` then `df` would be its copy. This is quite subtle, so I usually do not recommend such code unless you really know what you do. If you want a copy always better do `df = copy(_table)`

**Comment by yoh-meyers** [comment] 2022-07-08 10:21
Sure, here is full minimal example:

1 - Create a `DataFrameDriver.jl` file:
```julia
import DataFrames
import Feather

_table = nothing
_table_name = ""

function init(table_name::String, df::DataFrames.DataFrame)
    global _table_name = table_name

    global _table = df
    file_save()
end

function file_load()
    global _table = Feather.materialize(_table_name * ".feather")
end

function file_save()
    Feather.write(_table_name * ".feather", _table)
end

function replace_column_values!(name::Symbol, value_old::Any, value_new::Any)
    df::DataFrames.DataFrame = deepcopy(_table)
    replace!(df[!, name], value_old => value_new)

    global _table = deepcopy(df)
    df = DataFrames.DataFrame()

    file_save()
end
```

2 - Create a `DemoTable.jl` file:
```julia
module DemoTable

include("DataFrameDriver.jl")

function create()
    init(
        "demo",
        DataFrames.DataFrame(A=1:4, B=["M", "F", "F", "M"], C=5:8)
    )
end

end
```

3 - Lastly create a `demo.jl` file:
```julia
import Pkg
Pkg.pkg"activate ."

import DataFrames

include("DemoTable.jl")
import .DemoTable

table = DemoTable
table.create()
table.file_load()
table.replace_column_values!(:B, "M", "Z")
table.file_load()
```

4 - Then run `julia demo.jl`

---

Idea is that any `<name>Table.jl` files can use `DataFrameDriver.jl` functionality.

**Comment by yoh-meyers** [comment] 2022-07-08 10:28
Above demo will work.

That said, I noticed 2 fixes, when using above for larger data:

1.  The `replace!` call has to wrapped in a task. So:

```julia
task = begin Threads.@spawn replace!() end
wait(task)
```

2. For some strange reason, even though `_table` is properly updated, I have to call `print` on a random row, before saving it to Feather.

I don't know why above 2 hacks (especially 2nd one) have fixed issue.

=> Maybe good idea to add in documentation that for large datasets calling `replace!` in background, one should consider wrapping it in a task call.

**Comment by bkamins** [comment] 2022-07-08 11:43
> Maybe good idea to add in documentation that for large datasets calling `replace!` in background, one should consider wrapping it in a task call.

This is a Base Julia function and has nothing to do with DataFrames.jl.

---

I have run your code and it works correctly on my machine (Win11, Julia 1.7.2) - I do not get the issue you report. Most likely this is OS related problem (not sure - maybe something related to how files are saved/cached?). You probably could report it in Feather.jl. However, note that Feather.jl is in low-maintanance mode, since it has been replaced by Arrow.jl. Maybe you can try porting your code to Arrow.jl and checking if the issue persists.

However, I am closing it in DataFrames.jl an it is for sure not an issue with DataFrames.jl (the `replace!` function that is causing your issues is not from DataFrames.jl).

**Closed as completed by bkamins** 2022-07-08 11:43 UTC
Labels: question
