### ISSUE TITLE
Show a (kind of) transposed DataFrame

### ISSUE THREAD

**Issue by scls19fr** [JuliaData/DataFrames.jl#2065] opened 2019-12-25 19:52 UTC
Hello,

I have a `DataFrame` like

```julia
2×9 DataFrame. Omitted printing of 3 columns
│ Row │ time     │ latitude             │ longitude              │ validity │ pressure_alt             │ gps_alt             │
│     │ Dates…   │ IGC.IGCLatitude      │ IGC.IGCLongitude       │ IGC…     │ IGC.IGCPressureAltitude  │ IGC.IGCGpsAltitude  │
├─────┼──────────┼──────────────────────┼────────────────────────┼──────────┼──────────────────────────┼─────────────────────┤
│ 1   │ 16:02:50 │ IGCLatitude(51.1189) │ IGCLongitude(-1.82138) │ Fix3D    │ IGCPressureAltitude(290) │ IGCGpsAltitude(432) │
│ 2   │ 16:02:55 │ IGCLatitude(51.119)  │ IGCLongitude(-1.82035) │ Fix3D    │ IGCPressureAltitude(290) │ IGCGpsAltitude(430) │
```

ie very few lines but larger number of columns.

Is there a way to display a "kind of" transposed DataFrame.

I'm not looking for a way to really transpose it... just for a way to print it differently with rows/columns inverted.

Kind regards

**Comment by scls19fr** [comment] 2019-12-25 19:56
I noticed https://github.com/JuliaData/DataFrames.jl/issues/1701 with could looks quite similar to this issue... but that's in fact quite different as I'm looking for a pretty printed tabular representation of this DataFrame (like shown previously but with rows and columns switched)

**Comment by bkamins** [comment] 2019-12-25 23:20
We do not support it AFAICT. But you can do something like:
```
DataFrame([[names(df)]; collect.(eachrow(df))], [:column; Symbol.(axes(df, 1))])
```

**Comment by scls19fr** [comment] 2019-12-26 08:38
Thanks @bkamins 
So why not implementing a transpose function which take `DataFrame` as input?

PS : new answer on SO thanks to you https://stackoverflow.com/questions/37668312/transpose-of-julia-dataframe/59485866#59485866

**Comment by bkamins** [comment] 2019-12-26 08:57
Could you give an example where it would be useful, given we have `eachrow` iterator and `stack`/`unstack`? The issue is that data frame can have heterogeneous columns so after transformation the data will not be stored efficiently + in both solutions you see that we create the column with column names artificially, so transpose of transpose is not identity. If you need to transpose just data (without column names) one can write `permutedims(Matrix(df))`.

**Comment by scls19fr** [comment] 2019-12-26 09:15
So, as transposing lead to problem with data storing, why not considering implementing a function which just prints DataFrame by switching rows and columns ie without really transposing (that was the sense of "kind of").

**Comment by bkamins** [comment] 2019-12-26 14:23
It is not a "problem" but rather it is something that would not be really recommended for performance reasons.

Regarding your question. Sure - this could be doable, so I am reopening the issue.
Feel free to open a PR if you wish to work on it. Normally we try to provide support for text/plain, HTML and LaTeX mimes. Thank you!

**Comment by pdeffebach** [comment] 2020-01-10 15:51
`describe` with `first` as one of the functions you want to have displayed could also help here.

**Comment by bkamins** [comment] 2020-11-08 07:33
@ronisbr - does PrettyTables.jl support something like this?

**Comment by ronisbr** [comment] 2020-11-09 01:35
No, it doesn’t, but seems to be a very good feature to be implemented :)

**Comment by bkamins** [comment] 2020-11-09 07:06
OK - so a typical question. Do you feel it is a general feature for PrettyTables.jl? (and if so maybe move it there?)

**Comment by ronisbr** [comment] 2020-11-09 11:13
Yes, this should be moved to PrettyTable.jl!

**Comment by bkamins** [comment] 2020-11-09 11:46
OK - so closing it here.

**Closed by bkamins** 2020-11-09 11:46 UTC
Labels: display, non-breaking
