### ISSUE TITLE
CSV.read cannot detect "Time" type string

### ISSUE THREAD

**Issue by evveric** [JuliaData/DataFrames.jl#2005] opened 2019-11-08 04:48 UTC
I have a DataFrame with a "Time" column

I CSV.write this DataFrame to a File, then CSV.read it back

DataFrame does not recognize it is a TIme, it reads as a "String"

How to fix it? Thank you

```
df = DataFrame(thistime=[Time(10,0,0), Time(12,0,0)])

CSV.write(raw"c:\temp\testtime.csv", df)

df2 = CSV.read(raw"c:\temp\testtime.csv") |> DataFrame

println(eltypes(df2))
```

DataType[String]

**Comment by quinnj** [comment] 2019-11-08 06:02
Duplicate of CSV.jl issue

**Closed by quinnj** 2019-11-08 06:02 UTC
