### ISSUE TITLE
column names of aggregated DataFrame with anonymous functions

### ISSUE THREAD

**Issue by pfarndt** [JuliaData/DataFrames.jl#1276] opened 2017-11-14 15:44 UTC
When using an anonymous functions to generate an aggregated DataFrame the column names are not reproducible and inconvenient for further usage:

```
using DataFrames

d = DataFrame(g = [1,1,2,2], v=1:4)

println(names(aggregate(d, :g, x->sum(x))))
println(names(aggregate(d, :g, x->sum(x))))
```

This code produces:
```
Symbol[:g, Symbol("v_#1")]
Symbol[:g, Symbol("v_#3")]
```
although the last two commands are identical.

The documentation is promising names like `v_\lambda1` at this point. I am using Julia v0.6.0.

IMO the function `_fnames` in [https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/utils.jl](url) should be adjusted for new versions of julia.

**Comment by cjprybol** [comment] 2017-11-14 18:31
> not reproducible

I was able to reproduce this
```julia
julia> using DataFrames

julia> d = DataFrame(g = [1,1,2,2], v=1:4)
4×2 DataFrames.DataFrame
│ Row │ g │ v │
├─────┼───┼───┤
│ 1   │ 1 │ 1 │
│ 2   │ 1 │ 2 │
│ 3   │ 2 │ 3 │
│ 4   │ 2 │ 4 │

julia> println(names(aggregate(d, :g, x->sum(x))))
Symbol[:g, Symbol("v_#1")]

julia> println(names(aggregate(d, :g, x->sum(x))))
Symbol[:g, Symbol("v_#3")]
```

The names of the columns are the function identifiers. Here's another fresh session to show the identifiers of the anonymous functions, which you'll see match the column names, and are again reproducible. 

```julia
julia> x->sum(x)
(::#1) (generic function with 1 method)

julia> x->sum(x)
(::#3) (generic function with 1 method)
```
> inconvenient for further usage

The previously used lambda syntax has no relation (aside from order) to the actual functions that were used to create the data and hence was removed.  Unfortunately, it is not yet possible to extract the original code of an anonymous function by its identifier (see https://github.com/JuliaLang/julia/issues/2625#issuecomment-306270254), although in principle if that is added as a language feature then using the identifiers of the anonymous functions will provide both a stable identifier as well as a way to recover the function associated with that identifier. Currently, only the "stable identifier" part is supported while the lambda syntax cannot support either.

If you would like the columns to have specific names, you simply need to use named functions. For example, in the case that you provided using the anonymous function isn't recommended and you can simply use the `sum` function instead of wrapping it into an anonymous function with `x -> sum(x)`.
```julia
julia> names(aggregate(d, :g, sum))
2-element Array{Symbol,1}:
 :g
 :v_sum
```

alternatively, you can retain the lambda naming by giving your anonymous functions that name
```julia
julia> λ1(x) = sum(x)
λ1 (generic function with 1 method)

julia> names(aggregate(d, :g, λ1))
2-element Array{Symbol,1}:
 :g
 :v_λ1
```

You are correct that the documentation for that section is out of date, it will be corrected after https://github.com/JuliaData/DataFrames.jl/pull/1252 is merged. The `_ fnames` should have already been removed. If you'd like to contribute a PR to delete it, that would be great!

**Comment by nalimilan** [comment] 2017-11-14 18:55
The presence of a `#` is really annoying since it makes the symbol non-standard. Maybe we should replace it with another symbol, probably an ASCII one so that it's easy to type (`f`?).

**Comment by pfarndt** [comment] 2017-11-14 19:30
You got the point - the `#` is annoying. 

To change it to something else (e.g. `f`) only solves half of the problem, since I might call such an `aggregate` statement (with more than one and more complicated anonymous function than just a `sum`) several times and _use_ the resulting column further on. Right now I would have to inquire its name by calling `names` and calculating (since I might want to apply the anonymous function to several columns) its position. Therefore  the  "previously used lambda syntax" that "has no relation (aside from order) to the actual functions", would be _very_ helpful, because it has all the information one needs, i.e. column name and which of my anonymous functions went over it.

**Comment by nalimilan** [comment] 2017-11-14 21:02
So you mean, just use `f1`, `f2`...? Why not.

**Comment by bkamins** [comment] 2018-12-14 09:53
Closing as #1576 fixed this

**Closed by bkamins** 2018-12-14 09:53 UTC
Labels: Hacktoberfest, intro issue
