### ISSUE TITLE
Markdown display

### ISSUE THREAD

**Issue by yakir12** [JuliaData/DataFrames.jl#1167] opened 2017-02-21 13:44 UTC
It would be useful if `writetable` had an option to save the table as a markdown table (the repl output seems to already be in markdown).

**Comment by ExpandingMan** [comment] 2017-02-21 14:21
+1 for this, or, better yet, a LaTeX tabular.  I think I/O functionality either has been or will be moved to another package though, so I'm not sure whether this is still the appropriate place for issues like this.

**Comment by nalimilan** [comment] 2017-02-21 14:23
`writetable` is meant to write CSV files, and it's going to be deprecated in favor of CSV.jl anyway. Markdown output should rather go  through the `show` machinery, just like we currently do for HTML and LaTeX (in DataTables only, see [this file](https://github.com/JuliaData/DataTables.jl/blob/master/src/abstractdatatable/io.jl)).

**Comment by ExpandingMan** [comment] 2017-02-21 14:38
I wasn't aware the LaTeX output functionality existed, that is very cool indeed!

**Comment by quinnj** [comment] 2017-02-21 16:33
It would actually be pretty easy to write a `MarkdownTables.jl` package that implemented the DataStreams interface. Then you read/write a markdown table from any other DataStream package.

**Comment by yakir12** [comment] 2017-02-22 09:44
I agree that this functionality doesn't need to live in DataFrames. [Markdown.jl](https://github.com/JuliaArchive/Markdown.jl) lives in Base, and therefore it should be slim (right?), but there could be many other functionalities that become relevant for such a package. I'm mainly thinking of use-cases involving [pandoc](http://pandoc.org/), where you'd parse some data you have in julia (e.g. as a DataFrame) to markdown, and then use pandoc to convert that into whatever you want (LaTeX, HTML, etc).

**Comment by korsbo** [comment] 2019-01-21 19:07
It is possible to generate both markdown and LaTeX tables from a DataFrame using [Latexify.jl](https://github.com/korsbo/Latexify.jl). If you feel that Latexify is not doing a sufficiently good job of this, then feel free to post an issue there (or submit a PR).

**Comment by bkamins** [comment] 2019-07-25 02:17
I think this should be a generic functionality for any type that supports Tables.jl API so it is probably outside DataFrames.jl so I am closing this (feel free to reopen if you think we should discuss it more here).

**Closed by bkamins** 2019-07-25 02:17 UTC

**Comment by nalimilan** [comment] 2019-07-25 13:15
Given that the code for that should be pretty simple (basically like CSV), it wouldn't be absurd to support that in DataFrames.jl if somebody wants to make a PR. If we want to put this in a separate package, better have a single package taking any table in the Tables.jl sense and supporting a variety of MIME types. Then DataFrames could use it to implement `show(io, mime, df)`.

**Comment by pgagarinov** [comment] 2021-04-13 18:05
@bkamins 

Documentation for `show` says:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/4868370/114599266-8c248680-9c9b-11eb-84f9-6040826aebf2.png">

However, passing `tf=tf_format` into `show` doesn't seem to work:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/4868370/114599427-bf671580-9c9b-11eb-8901-eba16771f648.png">

And I have to call `pretty_table` directly to make it work:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/4868370/114599535-e887a600-9c9b-11eb-9ef0-bf47dd685456.png">

Is ignoring `tf` kwarg the expected behavior?

**Comment by bkamins** [comment] 2021-04-13 18:25
@ronisbr - could you please comment here? Maybe we need to update the docstring? Thank you!

**Comment by bkamins** [comment] 2021-04-13 18:28
Also here is what I get:
```
julia> using DataFrames

julia> show(DataFrame(a=1:3,b='x':'z'), tf=PrettyTables.tf_markdown)
3×2 DataFrame
 Row | a      b    
     | Int64  Char 
-----|-------------
   1 |     1  x
   2 |     2  y
   3 |     3  z
julia> PrettyTables.pretty_table(DataFrame(a=1:3,b='x':'z'), tf=PrettyTables.tf_markdown)
|     a |    b |
| Int64 | Char |
|-------|------|
|     1 |    x |
|     2 |    y |
|     3 |    z |
```
(and maybe this is what is expected?)

**Comment by ronisbr** [comment] 2021-04-13 20:52
It is doing what it is supposed to. The problem is that the other configurations in DataFrames hide vertical lines. Hence, in this case, you will also need to pass `vlines = :all`.

**Comment by bkamins** [comment] 2021-04-13 21:17
Thank you (this is what I assumed, but unfortunately I have not mastered all options of PrettyTables.jl yet)

**Comment by ronisbr** [comment] 2021-04-13 21:46
No problem! Feel free to ping me in every issue related to PrettyTables.
