### ISSUE TITLE
Exception_access_violation julia

### ISSUE THREAD

**Issue by anthonyagudelox3** [JuliaData/DataFrames.jl#1858] opened 2019-06-24 15:24 UTC
Hello, I am trying to use MySQL to access my local database and submit a query, however when I run the following code I get this error. This seems like a privileges issue however, I am unsure on how to resolve it.
This was done on Julia v0.7.0, on a Windows 10 PC.

'analysis = "ptb"
con = MySQL.connect("127.0.0.1", "root", password, db = "$(analysis)_pubmed")

command = """SELECT DISTINCT g.pmid, g.hgnc_id, count(*) as count
FROM pubtator_genes g
WHERE g.passage_type="abstract"
GROUP BY g.pmid, g.hgnc_id
ORDER BY count;"""

abstract_df = BioMedQuery.DBUtils.db_query(con, command)
`

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6fc4ce0b -- jl_get_nth_field at /home/Administrator/buildbot/worker/package_win32/build/src\datatype.c:837
in expression starting at untitled-f9149ad6a13ab84805b2ee55adc59766:19
jl_get_nth_field at /home/Administrator/buildbot/worker/package_win32/build/src\datatype.c:837
jl_f_getfield at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:757
getproperty at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\utils.jl:27 [inlined]
macro expansion at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\utils.jl:55 [inlined]
eachcolumn at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\utils.jl:47
unknown function (ip: 10DDF932)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
buildcolumns at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\fallbacks.jl:95 [inlined]
columns at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\fallbacks.jl:149 [inlined]
Type at C:\Users\Thor.julia\packages\DataFrames\IKMvt\src\other\tables.jl:21
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
|> at .\operators.jl:813
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
db_query at C:\Users\Thor.julia\packages\BioMedQuery\K4kwC\src\DBUtils\mysql_db_utils.jl:87
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:799
unknown function (ip: FFFFFFFE)
unknown function (ip: 1726EA9F)
unknown function (ip: 00000001)
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:808
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:831
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:841
jl_load_file_string at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:871
include_string at .\loading.jl:1002
include_string at C:\Users\Thor.julia\packages\CodeTools\xGemk\src\eval.jl:30
unknown function (ip: 10DA2EF1)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
#116 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:94
withpath at C:\Users\Thor.julia\packages\CodeTools\xGemk\src\utils.jl:30
withpath at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:46 [inlined]
#115 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:93 [inlined]
with_logstate at .\logging.jl:397
with_logger at .\logging.jl:493 [inlined]
#114 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:92 [inlined]
hideprompt at C:\Users\Thor.julia\packages\Atom\OZKl0\src\repl.jl:87
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
macro expansion at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:91 [inlined]
#113 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:86
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
handlemsg at C:\Users\Thor.julia\packages\Atom\OZKl0\src\comm.jl:164
unknown function (ip: 10D85D2A)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1538 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:563
#19 at .\task.jl:262
unknown function (ip: 10D82BB6)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1538 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win32/build/src\task.c:268
wmain at /home/Administrator/buildbot/worker/package_win32/build/ui\repl.c:233
Allocations: 37273076 (Pool: 37270984; Big: 2092); GC: 195

In addition it seems like running the following command gives a similar issue.

`MySQL.Query(con, command) |> DataFrame
`

WARNING: both DataFrames and Base export "showall"; uses of it in module Main must be qualified
MySQL.Query{true,(:pmid, :hgnc_id, :count),Tuple{Union{Missing, Int32},Union{Missing, Int32},Int64}}(MySQL.Result(Ptr{Nothing} @0x00eac8e0), Ptr{Ptr{Int8}} @0x250e7f60, 3, 2294)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6fc4ce0b -- jl_get_nth_field at /home/Administrator/buildbot/worker/package_win32/build/src\datatype.c:837
in expression starting at untitled-f9149ad6a13ab84805b2ee55adc59766:23
jl_get_nth_field at /home/Administrator/buildbot/worker/package_win32/build/src\datatype.c:837
jl_f_getfield at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:757
getproperty at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\utils.jl:27 [inlined]
macro expansion at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\utils.jl:55 [inlined]
eachcolumn at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\utils.jl:47
unknown function (ip: 10EC1012)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
buildcolumns at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\fallbacks.jl:95 [inlined]
columns at C:\Users\Thor.julia\packages\Tables\0M7Kt\src\fallbacks.jl:149 [inlined]
Type at C:\Users\Thor.julia\packages\DataFrames\IKMvt\src\other\tables.jl:21
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
|> at .\operators.jl:813
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:799
unknown function (ip: FFFFFFFE)
unknown function (ip: 1F4C288F)
unknown function (ip: 00000001)
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:808
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:831
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:841
jl_load_file_string at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:871
include_string at .\loading.jl:1002
include_string at C:\Users\Thor.julia\packages\CodeTools\xGemk\src\eval.jl:30
unknown function (ip: 10E3BD31)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
#116 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:94
withpath at C:\Users\Thor.julia\packages\CodeTools\xGemk\src\utils.jl:30
withpath at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:46 [inlined]
#115 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:93 [inlined]
with_logstate at .\logging.jl:397
with_logger at .\logging.jl:493 [inlined]
#114 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:92 [inlined]
hideprompt at C:\Users\Thor.julia\packages\Atom\OZKl0\src\repl.jl:87
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
macro expansion at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:91 [inlined]
macro expansion at C:\Users\Thor.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
#113 at C:\Users\Thor.julia\packages\Atom\OZKl0\src\eval.jl:86
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
handlemsg at C:\Users\Thor.julia\packages\Atom\OZKl0\src\comm.jl:164
unknown function (ip: 10E7182A)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1538 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:563
#19 at .\task.jl:262
unknown function (ip: 10E6FBD6)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1538 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win32/build/src\task.c:268
wmain at /home/Administrator/buildbot/worker/package_win32/build/ui\repl.c:233
Allocations: 67020851 (Pool: 67017371; Big: 3480); GC: 360

**Comment by bkamins** [comment] 2019-06-24 15:30
It seems that you are not using the latest version of DataFrames.jl (this is an error that was present some time ago and we thought it got fixed). Could you please update all packages and rerun your code (in particular Tables.jl and DataFrames.jl should be updated)?

**Comment by anthonyagudelox3** [comment] 2019-06-24 16:23
I ran; 
`using Pkg

Pkg.update("DataFrames")
Pkg.update("Tables")`

And am still getting the same issue. 



Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6fc4ce0b -- jl_get_nth_field at /home/Administrator/buildbot/worker/package_win32/build/src\datatype.c:837
in expression starting at C:\Users\Thor\Documents\Machine Learning\Work\SQLexample.jl:22
jl_get_nth_field at /home/Administrator/buildbot/worker/package_win32/build/src\datatype.c:837
jl_f_getfield at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:757
getproperty at C:\Users\Thor\.julia\packages\Tables\0M7Kt\src\utils.jl:27 [inlined]
macro expansion at C:\Users\Thor\.julia\packages\Tables\0M7Kt\src\utils.jl:55 [inlined]
eachcolumn at C:\Users\Thor\.julia\packages\Tables\0M7Kt\src\utils.jl:47
unknown function (ip: 26E56842)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
buildcolumns at C:\Users\Thor\.julia\packages\Tables\0M7Kt\src\fallbacks.jl:95 [inlined]
columns at C:\Users\Thor\.julia\packages\Tables\0M7Kt\src\fallbacks.jl:149 [inlined]
Type at C:\Users\Thor\.julia\packages\DataFrames\IKMvt\src\other\tables.jl:21
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
|> at .\operators.jl:813
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:799
unknown function (ip: FFFFFFFE)
unknown function (ip: 183A7F0F)
unknown function (ip: 00000001)
jl_interpret_toplevel_thunk at /home/Administrator/buildbot/worker/package_win32/build/src\interpreter.c:808
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win32/build/src\toplevel.c:831
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:841
jl_load_file_string at /home/Administrator/buildbot/worker/package_win32/build/src\ast.c:871
include_string at .\loading.jl:1002
include_string at C:\Users\Thor\.julia\packages\CodeTools\xGemk\src\eval.jl:30
unknown function (ip: 10E16071)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
#116 at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\eval.jl:94
withpath at C:\Users\Thor\.julia\packages\CodeTools\xGemk\src\utils.jl:30
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_invoke at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:42
withpath at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\eval.jl:46 [inlined]
#115 at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\eval.jl:93 [inlined]
with_logstate at .\logging.jl:397
with_logger at .\logging.jl:493 [inlined]
#114 at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\eval.jl:92 [inlined]
hideprompt at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\repl.jl:87
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
macro expansion at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\eval.jl:91 [inlined]
macro expansion at C:\Users\Thor\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
#113 at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\eval.jl:86
jl_fptr_args at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:1839
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
handlemsg at C:\Users\Thor\.julia\packages\Atom\OZKl0\src\comm.jl:164
unknown function (ip: 10EC332A)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1538 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win32/build/src\builtins.c:563
#19 at .\task.jl:262
unknown function (ip: 10EC16D6)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win32/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win32/build/src\julia.h:1538 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win32/build/src\task.c:268
wmain at /home/Administrator/buildbot/worker/package_win32/build/ui\repl.c:233
Allocations: 77101065 (Pool: 77095823; Big: 5242); GC: 414

**Comment by bkamins** [comment] 2019-06-24 16:56
@quinnj - this seems to be Tables.jl related.

**Comment by quinnj** [comment] 2019-06-24 19:26
Duplicate of https://github.com/JuliaDatabases/MySQL.jl/issues/126

**Closed by quinnj** 2019-06-24 19:26 UTC

**Comment by bkamins** [comment] 2019-06-24 19:58
@quinnj - thank you. I knew I saw it somewhere, but could not remember where.
