### ISSUE TITLE
Variance in runtime reduction functions

### ISSUE THREAD

**Issue by fieldofnodes** [JuliaData/DataFrames.jl#2956] opened 2021-12-03 20:31 UTC
# Issue
I encountered a long run time to compute a row-wise reduction function (summing across columns). After a conversation on Slack I am opening an issue.
## Goal  
I wanted to create a new column that would be the `ByRow` sum across the columns of `df`.

## Data
This data has numbered columns as the header from **30** to **355** they are not to be included in the summation.
**Link to data:** [Data](https://drive.google.com/file/d/1BzWp-SB3exk07QjMpGpV1lAYiG9Xz3UH/view?usp=sharing)
I consider that `first` and `last` refer to the first and last columns of a dataframe, `df`.

### Version 01
```
@time version1 @chain df begin
	select(_, Between(first,last))
	select(_, (:) => (+) => :Abundance)
end
```
Time: `63.098904 seconds (455.54 M allocations: 16.426 GiB, 14.04% gc time, 63.49% compilation time)`

### Version 02
```
@time version2 = @chain df begin
	select(_, Between(first,last))
	Matrix
	sum(_,dims = 2)
end
```
Time:  `0.004102 seconds (1.66 k allocations: 10.598 MiB)`

### Version 03
```
@time version3 = @chain df begin
	select(_, 
		AsTable(Between(first, last)) => ByRow(sum) => :Abundance)
end
```
Time:  `3.410094 seconds (1.47 M allocations: 82.979 MiB, 93.44% compilation time)`
2nd time run: `0.201551 seconds (700.12 k allocations: 38.060 MiB)`

### Version 04
```
@time version4 @chain df begin 
    select(Between(first, last); copycols = false)
    eachcol
    sum
end
```
Time:  10.001236 seconds (1.01 k allocations: 5.307 MiB)`
2nd time run:  `0.001622 seconds (1.01 k allocations: 5.307 MiB)`

```
reduce(+, eachcol(df)) 
```
Time: `0.110990 seconds (65.57 k allocations: 9.220 MiB, 98.15% compilation time)`

```
sum(eachcol(df1))
```
Time: `0.002187 seconds (646 allocations: 5.239 MiB)`

## Issues
I ran this in Pluto as opposed to the terminal or another editor.

Version 1 had a really long run time.

Is there a bug here or a Pluto issue?

**Version information**
```Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```
**Package status**
```
     Status `~/Projects/lrcfs_MLAI_projects/09_lrcfs_large_file_operations/Project.toml`
  [336ed68f] CSV v0.9.11
  [13f3f980] CairoMakie v0.6.6
  [8be319e6] Chain v0.4.8
  [a93c6f00] DataFrames v1.3.0
  [1313f7d8] DataFramesMeta v0.10.0
  [d872a56f] ElectronDisplay v1.0.1
  [72696420] FileTrees v0.3.3
  [e9467ef8] GLMakie v0.4.7
  [c91e804a] Gadfly v1.3.4
  [ee78f7c6] Makie v0.15.3
  [91a5bcdd] Plots v1.25.0
  [c3e4b0f8] Pluto v0.17.2
  [7f904dfe] PlutoUI v0.7.21
  [276b4fcb] WGLMakie v0.4.7
  [8ba89e20] Distributed
```

[Uploading columns2sum4IssueDataFrames.csv…]()

**Comment by bkamins** [comment] 2021-12-03 20:50
I read your data using:
```
df = CSV.read("columns2sum4IssueDataFrames.csv", DataFrame)
```
and set `first=1`, and `last=324`.

Now I run your codes (each run twice to see compilation effects):
```
julia> @time @chain df begin
               select(_, Between(first,last))
               select(_, (:) => (+) => :Abundance)
       end;
  0.878118 seconds (2.81 M allocations: 175.415 MiB, 3.10% gc time, 99.65% compilation time)

julia> @time @chain df begin
               select(_, Between(first,last))
               select(_, (:) => (+) => :Abundance)
       end;
  0.004550 seconds (1.78 k allocations: 10.571 MiB)

julia> @time @chain df begin
               select(_, Between(first,last))
               Matrix
               sum(_,dims = 2)
       end;
  0.197101 seconds (574.74 k allocations: 40.742 MiB, 98.07% compilation time)

julia> @time @chain df begin
               select(_, Between(first,last))
               Matrix
               sum(_,dims = 2)
       end;
  0.041162 seconds (1.35 k allocations: 10.588 MiB, 90.88% gc time)

julia> @time @chain df begin
               select(_,
                       AsTable(Between(first, last)) => ByRow(sum) => :Abundance)
       end;
  0.663962 seconds (2.56 M allocations: 152.551 MiB, 4.62% gc time, 99.88% compilation time)

julia> @time @chain df begin
               select(_,
                       AsTable(Between(first, last)) => ByRow(sum) => :Abundance)
       end;
  0.000520 seconds (488 allocations: 95.484 KiB)

julia> @time @chain df begin
           select(Between(first, last); copycols = false)
           eachcol
           sum
       end;
  0.030562 seconds (46.41 k allocations: 8.054 MiB, 95.20% compilation time)

julia> @time @chain df begin
           select(Between(first, last); copycols = false)
           eachcol
           sum
       end;
  0.000856 seconds (1.01 k allocations: 5.307 MiB)

julia> @time reduce(+, eachcol(df));
  0.042015 seconds (88.71 k allocations: 10.353 MiB, 96.71% compilation time)

julia> @time reduce(+, eachcol(df));
  0.002027 seconds (649 allocations: 5.239 MiB)

julia> @time sum(eachcol(df));
  0.002055 seconds (647 allocations: 5.239 MiB)

julia> @time sum(eachcol(df));
  0.002154 seconds (647 allocations: 5.239 MiB)
```
I test in on Julia 1.7.0 and DataFrames.jl 1.3.0 in the terminal.

In summary: I cannot reproduce it.

This is most likely Pluto.jl issue so pinging @fonsp.

**Comment by fieldofnodes** [comment] 2021-12-03 20:58
Great. Thanks for the feedback

**Comment by fieldofnodes** [comment] 2021-12-03 21:19
I re-ran this in the terminal
```
@time @chain df begin
               select(_, Between(first,last))
               select(_, (:) => (+) => :Abundance)
       end;

1.396892 seconds (2.81 M allocations: 175.799 MiB, 1.86% gc time, 99.63% compilation time)
0.006648 seconds (1.78 k allocations: 10.571 MiB)

 @time @chain df begin
               select(_, Between(first,last))
               Matrix
               sum(_,dims = 2)
       end;

0.294048 seconds (575.31 k allocations: 40.791 MiB, 98.38% compilation time)
0.004938 seconds (1.35 k allocations: 10.588 MiB)

@time @chain df begin
               select(_,
                       AsTable(Between(first, last)) => ByRow(sum) => :Abundance)
       end;

0.881510 seconds (2.56 M allocations: 152.677 MiB, 3.49% gc time, 99.85% compilation time)
0.000665 seconds (488 allocations: 95.484 KiB)

@time @chain df begin
    select(Between(first, last); copycols = false)
    eachcol
    sum
end;

0.058016 seconds (48.34 k allocations: 8.179 MiB, 95.43% compilation time)
0.003364 seconds (1.01 k allocations: 5.307 MiB)

@time reduce(+, eachcol(df));

0.062777 seconds (88.68 k allocations: 10.353 MiB, 95.09% compilation time)
0.004550 seconds (649 allocations: 5.239 MiB)

@time sum(eachcol(df));

0.003290 seconds (647 allocations: 5.239 MiB)
0.003101 seconds (647 allocations: 5.239 MiB)
```

**Comment by fieldofnodes** [comment] 2021-12-03 21:33
From Pluto
```
@time @chain df begin
    select(_, Between(first,last))
    select(_, (:) => (+) => :Abundance)
end;
1.850716 seconds (2.38 M allocations: 150.478 MiB, 99.56% compilation time)
0.007846 seconds (1.77 k allocations: 10.571 MiB)

@time @chain df begin
    select(_, Between(first,last))
    Matrix
    sum(_,dims = 2)
end;
0.530112 seconds (330.39 k allocations: 28.797 MiB, 13.01% gc time, 98.32% compilation time)
0.008407 seconds (1.66 k allocations: 10.598 MiB)

@time @chain df begin
    select(_,
            AsTable(Between(first, last)) => ByRow(sum) => :Abundance)
end;
1.510969 seconds (2.71 M allocations: 159.569 MiB, 5.03% gc time, 99.68% compilation time)
0.004783 seconds (1.13 k allocations: 134.938 KiB)


@time @chain df begin
    select(Between(first, last); copycols = false)
    eachcol
    sum
end;
0.059772 seconds (2.08 k allocations: 5.350 MiB, 89.58% compilation time)
0.006824 seconds (1.66 k allocations: 5.327 MiB)

@time reduce(+, eachcol(df));
0.006471 seconds (647 allocations: 5.239 MiB)
0.006399 seconds (647 allocations: 5.239 MiB)

@time sum(eachcol(df));
0.006854 seconds (646 allocations: 5.239 MiB)
0.057675 seconds (646 allocations: 5.239 MiB, 87.37% gc time)
```

**Comment by bkamins** [comment] 2022-01-06 20:29
I am closing this as I do not see anything more to do with it on DataFrames.jl side.

**Closed by bkamins** 2022-01-06 20:29 UTC
Labels: performance
