### ISSUE TITLE
append! broken with PooledArray column type

### ISSUE THREAD

**Issue by tk3369** [JuliaData/DataFrames.jl#1816] opened 2019-05-22 01:06 UTC
The latest CSV package uses PooledArrays but it doesn't work well with DataFrames.   

```julia
julia> df = CSV.File(download("https://gist.githubusercontent.com/tk3369/9a005ffbf5f1bf7648cb4558f72e66e7/raw/5a6b6a8d6a4e69fca6fe788d87ddd55f6498af25/test.csv")) |> DataFrame;

julia> df2 = deepcopy(df);

julia> append!(df, df2)
ERROR: MethodError: no method matching append!(::PooledArrays.PooledArray{String,UInt32,1,Array{UInt32,1}}, ::PooledArrays.PooledArray{String,UInt32,1,Array{UInt32,1}})
Closest candidates are:
  append!(::DataFrame, ::Any) at C:\Users\tkwong\.julia\packages\DataFrames\m9gd9\src\other\tables.jl:39
  append!(::Array{#s72,1} where #s72, ::AbstractArray{T,1} where T) at array.jl:893
  append!(::Array{T,1} where T, ::Any) at array.jl:900
  ...
```

**Comment by bkamins** [comment] 2019-05-22 04:37
Thank you for reporting this. There is an issue opened to fix it here https://github.com/JuliaComputing/PooledArrays.jl/pull/23.

**Comment by nalimilan** [comment] 2019-05-26 20:32
Closing since that's not a bug in DataFrames.

**Closed by nalimilan** 2019-05-26 20:32 UTC
