### ISSUE TITLE
Line shift in MySQL queries

### ISSUE THREAD

**Issue by cadoubs** [JuliaData/DataFrames.jl#1788] opened 2019-04-26 16:23 UTC
On version v0.18.0, the `MySQL.Query(D, "SELECT * FROM test.table") |> DataFrame`
returns a shifted table from the query, ie the first line is missing and an imaginary last line is added.
> 2×2 DataFrame
> │ Row │ key   │ value   │
> │     │ Int32 │ String⍰ │
> ├─────┼───────┼─────────┤
> │ 1   │ 2     │ Two     │
> │ 2   │ 0     │ #undef  │

This does not happen on v0.17.1
> 2×2 DataFrame
> │ Row │ key   │ value   │
> │     │ Int32 │ String⍰ │
> ├─────┼───────┼─────────┤
> │ 1   │ 1     │ One     │
> │ 2   │ 2     │ Two     │

**Comment by bkamins** [comment] 2019-04-26 20:54
Thank you for the report. What kind of object does `MySQL.Query` return?
Also I can diagnose the problem faster if you would indicate which `DataFrame` method gets called in your code (I do not use MySQL so it is hard for me to reproduce).

I understand that on 0.17.1 all worked fine?

**Comment by quinnj** [comment] 2019-04-26 20:57
I think I know what's going on here; it's the same issue I ran into w/ SQLite where because DataFrame calls `all` and starts iterating the `MySQL.Query`, we lose that first iteration of data.

**Comment by quinnj** [comment] 2019-04-26 20:57
So root cause involves #1785

**Comment by bkamins** [comment] 2019-04-26 21:00
But why has it started to pop up in 0.18.0 and was not present in 0.17.1? Anyway - what do you think could be a fix for this (is anything discussed in #1785 viable?)

**Comment by quinnj** [comment] 2019-04-26 21:13
The reason it started in 0.18 is because https://github.com/JuliaData/DataFrames.jl/commit/96eb818e1de9f72eff5ed87e277655e01bf57b59 is 0.18-only, which is where we call `all`

**Comment by bkamins** [comment] 2019-04-26 21:19
OK - now I remember adding it - sorry for the mess. I think we can drop the lines:
```
if applicable(iterate, x)
    if all(v -> v isa Pair{Symbol, <:AbstractVector}, x)
        return DataFrame(AbstractVector[last(v) for v in x], [first(v) for v in x])
    end
end
```
from this constructor. They were only added for consistency. We can accept only `AbstractVector` of `Pairs  `and then we are safe.

**Closed** 2019-04-27 13:11 UTC
