### ISSUE TITLE
ArgumentError: unable to construct DataFrame from JuliaDB.DIndexedTable

### ISSUE THREAD

**Issue by norci** [JuliaData/DataFrames.jl#1775] opened 2019-04-12 12:11 UTC
`
DataFrame(JuliaDB.loadtable(csvfilename))
`
This code can be run in Windows.
But in Linux, it got this error:

ArgumentError: unable to construct DataFrame from JuliaDB.DIndexedTable{...}
Stacktrace:
 [1] DataFrame(::JuliaDB.DIndexedTable{NamedTuple{...}) at /home/devel/.julia/packages/DataFrames/IKMvt/src/other/tables.jl:23
 [2] top-level scope at util.jl:156
 [3] top-level scope at In[5]:1

**Comment by bkamins** [comment] 2019-04-12 12:39
Can you please double check that in both environments you have exactly the same versions of Julia and all packages?

**Comment by bkamins** [comment] 2019-04-15 15:05
You only pass a version of DataFrames.jl not the whole environment. I cannot reproduce the error. But I think I see the reason of the error. You create a `table` without proper column names. JuliaDB.jl is different than DataFrames.jl in this respect and allows this. Then calling `Tables.columns` on such a value returns a `Tuple` of columns, and normally we expect a `NamedTuple`.

The problem seems more on the JuliaDB.jl vs Tables.jl interface. Maybe @piever or @quinnj could comment more.

**Comment by quinnj** [comment] 2019-07-12 03:12
I believe this should be fixed after a recent release of IndexedTables.jl; please comment here if you still have issues.

**Closed by quinnj** 2019-07-12 03:12 UTC
