### ISSUE TITLE
Add a method for displaying with markdown

### ISSUE THREAD

**Issue by pdeffebach** [JuliaData/DataFrames.jl#1483] opened 2018-08-16 04:56 UTC
DataFrames already has methods for printing a table to html and latex. It seems reasonable to add a markdown method for showing the table. 

To be honest, I would consider re-doing the show method entirely so as to get rid of these things: `├'

It's a bit odd for dataframes not to be copy-and-pastable. It shows up weird for me with inconsolata and sublime text. 

<img width="480" alt="screen shot 2018-08-15 at 11 49 55 pm" src="https://user-images.githubusercontent.com/23196228/44188914-f0a37800-a0e5-11e8-9872-dc37e89a8e1a.png">

Unfortunately, there is a proliferation of markdown table styles, and we don't want to support everything. This syntax is recognized by both github and pandoc (though but not standardized by commonmark).

```
| One | Two   |
|-----|-------|
| my  | table |
| is  | nice  |
```

| One | Two   |
|-----|-------|
| my  | table |
| is  | nice  |

Let me know if people think this is feasible. The funcitonality for printing dataframes to markdown already exists in a few other packages, so it by no means needs to live in DataFrames.

**Comment by nalimilan** [comment] 2018-09-02 13:58
Yes, that definitely sounds useful.

**Comment by nalimilan** [comment] 2018-09-20 17:39
Actually that's a duplicate of https://github.com/JuliaData/DataFrames.jl/issues/1167.

**Closed by nalimilan** 2018-09-20 17:39 UTC
