### ISSUE TITLE
Problems with restoring dataframes from JLD2

### ISSUE THREAD

**Issue by pevnak** [JuliaData/DataFrames.jl#1503] opened 2018-09-05 13:06 UTC
Hi,

I have the problem when loading DataFrame from a JLD file, as it crashes julia (totally). A reproducible error looks as
```
julia> using DataFrames, FileIO
julia> df2 = DataFrame(A = 1:10, B = ["x","y","z"][rand(1:3, 10)], C = rand(10))
julia> save("/tmp/test.jld2","df2",df2)
julia> load("/tmp/test.jld2","df2")

signal (11): Segmentation fault: 11
in expression starting at no file:0
index at /Users/user/.julia/packages/DataFrames/utxEh/src/dataframe/dataframe.jl:224 [inlined]
ncol at /Users/user/.julia/packages/DataFrames/utxEh/src/dataframe/dataframe.jl:229 [inlined]
insert_single_column! at /Users/user/.julia/packages/DataFrames/utxEh/src/dataframe/dataframe.jl:336
setindex! at /Users/user/.julia/packages/DataFrames/utxEh/src/dataframe/dataframe.jl:391 [inlined]
setproperty! at /Users/user/.julia/packages/DataFrames/utxEh/src/abstractdataframe/abstractdataframe.jl:241
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
macro expansion at /Users/user/.julia/packages/JLD2/xpVxm/src/data.jl:1276 [inlined]
jlconvert at /Users/user/.julia/packages/JLD2/xpVxm/src/data.jl:1232
read_data at /Users/user/.julia/packages/JLD2/xpVxm/src/dataio.jl:37
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
read_data at /Users/user/.julia/packages/JLD2/xpVxm/src/datasets.jl:149
load_dataset at /Users/user/.julia/packages/JLD2/xpVxm/src/datasets.jl:92
getindex at /Users/user/.julia/packages/JLD2/xpVxm/src/groups.jl:108
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
read at /Users/user/.julia/packages/JLD2/xpVxm/src/JLD2.jl:326
#45 at /Users/user/.julia/packages/JLD2/xpVxm/src/loadsave.jl:134 [inlined]
#jldopen#31 at /Users/user/.julia/packages/JLD2/xpVxm/src/loadsave.jl:4
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jldopen at /Users/user/.julia/packages/JLD2/xpVxm/src/loadsave.jl:2 [inlined]
#load#44 at /Users/user/.julia/packages/JLD2/xpVxm/src/loadsave.jl:133 [inlined]
load at /Users/user/.julia/packages/JLD2/xpVxm/src/loadsave.jl:133
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:563
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x10fe2bcaf)
unknown function (ip: 0x5)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:633
eval at ./boot.jl:319 [inlined]
#load#27 at /Users/user/.julia/packages/FileIO/kflOT/src/loadsave.jl:188
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
load at /Users/user/.julia/packages/FileIO/kflOT/src/loadsave.jl:172
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
#load#13 at /Users/user/.julia/packages/FileIO/kflOT/src/loadsave.jl:118
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
load at /Users/user/.julia/packages/FileIO/kflOT/src/loadsave.jl:118
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x110dc8e6f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:633
eval at ./boot.jl:319
eval_user_input at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
macro expansion at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:262
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1538 [inlined]
start_task at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:268
Allocations: 72807413 (Pool: 72789786; Big: 17627); GC: 159
Segmentation fault: 11
```

List of my packages is 
```
v0.7) pkg> st
    Status `~/.julia/environments/v0.7/Project.toml`
  [79e6a3ab] Adapt v0.3.1
  [c7e460c6] ArgParse v0.6.0
  [7d9fca2a] Arpack v0.2.3
  [5d742f6a] CSVFiles v0.9.1
  [a93c6f00] DataFrames v0.13.1
  [864edb3b] DataStructures v0.11.1
  [b4f34e82] Distances v0.7.3
  [31c24e10] Distributions v0.16.3
  [5789e2e9] FileIO v1.0.1
  [587475ba] Flux v0.6.6
  [28b8d3ca] GR v0.33.1
  [f67ccb44] HDF5 v0.10.1
  [d9be37ee] Homebrew v0.7.0
  [7073ff75] IJulia v1.11.1
  [916415d5] Images v0.15.1
  [c8e1da08] IterTools v1.0.0
  [033835bb] JLD2 v0.1.1
  [682c06a0] JSON v0.19.0
  [b1bec4e5] LIBSVM v0.3.0
  [50d2b5c4] Lazy v0.13.1
  [7f8f8fb0] LearnBase v0.2.2
  [9920b226] MLDataPattern v0.5.0+ #master (https://github.com/JuliaML/MLDataPattern.jl.git)
  [cc2ba9b6] MLDataUtils v0.4.0
  [872c559c] NNlib v0.4.1
  [f09324ee] Netpbm v0.2.1
  [5fb14364] OhMyREPL v0.3.0
  [429524aa] Optim v0.16.0
  [2dcacdae] ParallelDataTransfer v0.5.0
  [58dd65bb] Plotly v0.1.1
  [91a5bcdd] Plots v0.19.3
  [c46f51b8] ProfileView v0.4.0
  [92933f4c] ProgressMeter v0.6.0
  [d330b81b] PyPlot v2.6.3
  [295af30f] Revise v0.7.6
  [f2b01f46] Roots v0.7.2
  [2913bbd2] StatsBase v0.25.0
  [e0df1984] TextParse v0.6.0
  [37b6cedf] Traceur v0.1.1
  [b8865327] UnicodePlots v0.3.1
  [98cad3c8] ValueHistories v0.5.0
  [37e2e46d] LinearAlgebra
  [10745b16] Statistics
```

Thanks a lot. It is really a slowdown for me not to be able to load dataframes.

**Comment by nalimilan** [comment] 2018-09-05 13:53
Looks like a duplicate of https://github.com/simonster/JLD2.jl/issues/101. Closing since it appears to be a JLD2 bug. You can try using `serialize` or Feather.jl in the meantime.

**Closed by nalimilan** 2018-09-05 13:53 UTC
