### ISSUE TITLE
Showing unlimited number of columns on Jupyter Notebook?

### ISSUE THREAD

**Issue by bicycle1885** [JuliaData/DataFrames.jl#1757] opened 2019-03-29 07:43 UTC
In Jupyter Notebook (or JupyterLab), it seems an unlimited number of columns are shown as an output of a cell while the number of rows is limited. My data table contains 28,065 rows × 21,613 columns, and the horizontal scroll bar is very long and it takes a very long time to reander the table. I think there should be some reasonable cutoff (maybe 30 columns or so?) by default.

**Comment by bkamins** [comment] 2019-03-29 08:06
This issue keeps popping up. I think we should make `show` methods for HTML and LaTeX in sync with `show` for text/plain (i.e. use the same keyword arguments and have the same behavior).

@nalimilan - any objections. If not I can implement it (also `show` docstrings need some care).

**Comment by nalimilan** [comment] 2019-03-29 09:09
But how can we decide how many columns will fit in the display? Does Jupyter set `displaysize` so that we can at least do something approximate?

The ideal approach would be to use an interactive table with scrolling and lazy rendering, like TableView.jl (I think there are other packages implementing this). I guess Jupyter could use the Tables.jl interface for that.

**Comment by bkamins** [comment] 2019-03-29 09:17
We already read number of rows to display from `displaysize` we could also use it to determine number of columns (which typically will be 80).

Do you know who knows enough about interactive tables to give us a good advice how to proceed? (note, that in Jupyter we will still have to decide how to handle LaTeX which is not interactive, as PDF export uses LaTeX)

**Comment by nalimilan** [comment] 2019-03-29 09:22
OK, go for it then. Anyway it can't hurt if we keep printing everything when `displaysize` isn't defined.

IIRC @davidanthoff was part of the conversation about interactive HTML tables, but I don't remember where it happened.

**Comment by bkamins** [comment] 2019-03-29 09:37
AFAIK `displaysize` is always defined and defaults to 24x80.

**Comment by nalimilan** [comment] 2019-03-29 09:49
Ah, right. Fortunately the `:limit` `IOContext` property isn't set by default, so if we fall back to `false` as we do now for text output it should be OK.

**Comment by bkamins** [comment] 2019-03-29 09:58
Exactly.

**Comment by davidanthoff** [comment] 2019-03-29 14:10
The story for Jupyter is not simple, at this point... What used to work is that one could embed JavaScript in the HTML MIME bundle and thereby get interactivity into Jupyter Notebooks, but that no longer works on JuptyerLab, so I think that is essentially no longer an option.

So in general, if you want to add interactivity in JupyterLab, you need to install a JupyterLab extension that does that for you... WebIO does that behind the scenes, but I think that is probably too fragile for a package like DataFrames.jl by default. https://github.com/JuliaComputing/TableView.jl uses WebIO.jl, so that is an option for folks that are ok with that to get interactivity inside Jupyter.

I think the best bet is to wait and hope that JupyterLab adopts the `application/vnd.dataresource+json` MIME type. I _think_ that is on their roadmap, but not 100% sure. nteract already supports it, except in the currently shipping version they have a bug (it used to work just fine). The model there is that you just add support for that MIME type, serialize the table in a JSON format, and then the client provides an interactive table UI.  [Queryverse](https://www.queryverse.org/) supports that throughout for all packages already. https://github.com/queryverse/ElectronDisplay.jl also supports that.

**Comment by nalimilan** [comment] 2019-03-29 14:20
OK, thanks. But serializing to JSON could be very slow for large data sets, when we just want to render a small part.

**Comment by davidanthoff** [comment] 2019-03-29 15:33
Yes, agreed. I haven't seen any discussion re the large dataset problem around that... Maybe they plan to use arrow for that? But that still seems not ideal because presumably one would have to move everything over at once to jupyter. What would really be needed is some way for Jupyter to request paged versions of the data from the kernel...

**Comment by nalimilan** [comment] 2019-03-29 15:54
Yeah, maybe an extension based on Tables.jl is needed to transfer and render only the relevant data.

**Comment by quinnj** [comment] 2019-03-29 15:59
Happy to help support whatever's needed in Tables.jl. I haven't followed the discussion in detail, but I agree that having some api where the frontend could request "regions" of a dataset seems most sensible with paging horizontally/vertically as needed.

**Comment by davidanthoff** [comment] 2019-03-29 16:55
I think at least for JupyterLab we just have to wait for them to come up with some design for paging, I don't think the problem is on the julia end, there is just no design in Juptyer for this scenario ATM, as far as I can tell.

**Comment by bicycle1885** [comment] 2019-03-30 03:00
I think it is not necessary to fit in the display size. I just want to limit the output at some reasonable cutoff. The problem is showing an unlimited number of columns to the display.

**Comment by bkamins** [comment] 2019-03-30 14:26
I have proposed an initial idea of the implementation solving this problem in https://github.com/JuliaData/DataFrames.jl/pull/1761.

**Comment by bkamins** [comment] 2019-04-20 21:51
Closed by #1761. We probably can further refine it, however in the future we should switch to a better data frame rendering mechanism in general.

**Closed by bkamins** 2019-04-20 21:51 UTC

**Comment by bicycle1885** [comment] 2019-04-21 04:18
Thank you very much!
